name: build
on:
  push:
    branches: ["main"]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the changed files back to the repository.
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # It's needed for git-restore-mtime
      - name: Reset directories timestamp # Workaround for https://github.com/MestreLion/git-tools/issues/47
        run: find . -mindepth 1 -type d -not -iwholename '*.git*' -exec touch -t 197001010000 {} \;
      - name: Restore files timestamp
        uses: chetan/git-restore-mtime-action@v2 # Restore files original modification time to have deterministic zip bundles
      # - name: Setup upterm session
      #   uses: lhotari/action-upterm@v1
      - name: "Install FPSLocker patches"
        working-directory: ./Sources/NXVenom
        run: curl -L https://github.com/masagrator/FPSLocker-Warehouse/archive/refs/heads/main.zip > main.zip
        run: unzip main.zip
        run: cp -r FPSLocker-Warehouse-main/SaltySD/plugins SaltySD/ && rm -rf FPSLocker-Warehouse-main
      - name: "Compile OCBundle (legacy)"
        working-directory: ./Sources/NXVenom
        run: zip -qqrX ../../OCBundle.zip ./
      - name: "Compile NXVenom"
        working-directory: ./Sources/NXVenom
        run: zip -qqrX ../../NXVenom.zip ./
      - name: "Compile AIO"
        working-directory: ./Sources/AIO
        run: zip -qqrX ../../AIO.zip ./
      - name: "Compile EOS Wizard"
        working-directory: ./Sources/NXVenom
        run: zip -qqrX "../../EOS Wizard.zip" "./switch/.packages/EOS Wizard" ./switch/.overlays/ovlmenu.ovl
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Build: Compile Bundle"
          file_pattern: "*.zip"
